[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo
    robtillaart/DHT20
    marcoschwartz/LiquidCrystal_I2C
